services:
  php:
    image: "marxredstar/aoc2022fullstack_php"
    networks:
      - backend
    volumes:
     - ./app:/var/www/html/
  apache:
    image: "marxredstar/aoc2022fullstack_apache"
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
     - ./app:/var/www/html/
networks:
  frontend:
  backend:
